###
POST http://localhost:4000/api/auth/new
Content-Type: application/json

{
  "name": "Peter Parker",
  "email": "spiderman@marvel.com",
  "password": "theamazingspiderman"
}

###
POST http://localhost:4000/api/auth/
Content-Type: application/json

{
  "email": "spiderman@marvel.com",
  "password": "theamazingspiderman"
}

###
POST http://localhost:4000/api/auth/renew
Content-Type: application/json

{}