### Register
POST http://localhost:4000/api/auth/new
Content-Type: application/json

{
  "name": "Bruce Wayne",
  "email": "batman@dc.com",
  "password": "0123456789"
}

### Login
POST http://localhost:4000/api/auth/
Content-Type: application/json

{
  "email": "spiderman@marvel.com",
  "password": "0123456789"
}

### Renew Token
GET http://localhost:4000/api/auth/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MmM1M2VmNDdiNGNmYWZmODAxN2UxNzAiLCJuYW1lIjoiUGV0ZXIgUGFya2VyIiwiaWF0IjoxNjU3MTI2OTk4LCJleHAiOjE2NTcxMzA1OTh9.GqfNFjONQj1ikkkDxdlOwsDjhRMUPtBgBtkzIBHRp5c
