@host = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MmM1M2VmNDdiNGNmYWZmODAxN2UxNzAiLCJuYW1lIjoiUGV0ZXIgUGFya2VyIiwiaWF0IjoxNjU3MTM3MzcxLCJleHAiOjE2NTcxNDA5NzF9.VIWyzyaVIu8QsN9w-eUtC3GwubOwaKtO5vnVlfoIPx0

### Events List
GET {{host}}/api/events
x-token: {{token}}

### Create Event
POST {{host}}/api/events
Content-Type: application/json
x-token: {{token}}

{
  "title": "Junta con el proyect manager",
  "notes": "Se trataran temas de la planeación de sprint",
  "start": 1000000,
  "end": 1000100
}

### Update Event
PATCH {{host}}/api/events/62c5dcfe68842755ab0b7b27
Content-Type: application/json
x-token: {{token}}

{
  "title": "Junta con el project manager",
  "notes": "Se trazaran objectivos del proyecto para su evaluación"
}

### DELETE Event
DELETE {{host}}/api/events/123
x-token: {{token}}
